### PR TITLE
Replace CFtimestamp() with as_timestamp()

### PR DESCRIPTION
**Pull request by fabern**
## Description
The [recent update](https://github.com/pvanlaake/CFtime/commit/d0f0914bbe2ca99f40254d707614b959971347d3) of the package `CFtime` renamed the function `CFtimestamp()` to `as_timestamp()`.
The old function name was still working but gave a deprecation warning:
`"Function CFtimestamp()  is deprecated. Use as_timestamp() instead."`

## Related Issue
None documented yet.

### CODE REVIEW

**Comment by fabern** [comment]
Appveyor failure looks unrelated, perhaps due to something similar to [this](https://github.com/appveyor/ci/issues/2504?)

**Comment by fabern** [comment]
Since PR #124 added functionality, would you agree to increase the version number to 0.4 (alternatively to 0.3.1) and update the CRAN version?

**Comment by mdsumner** [comment]
thanks!

**Comment by mdsumner** [comment]
CRAN are on holidays so I'll have to wait a couple weeks

**Pull request merged**
